enum ActionTypes {
  FETCH_ARTICLES_REQUEST = `FETCH_ARTICLES_REQUEST`,
  FETCH_ARTICLES_SUCCESS = `FETCH_ARTICLES_SUCCESS`,
  FETCH_ARTICLES_FAILURE = `FETCH_ARTICLES_FAILURE`,
}

export default ActionTypes;